#!/bin/bash

roscore &
cd catkin_ws
source ./devel/setup.bash
catkin_make
sleep 1
rosrun bound_est Bound_Est
rosbag play /home/senne/catkin_ws/src/bound_est/src/resources/cone_files/KartingGenk.bag


