#!/bin/bash

cd ./catkin_ws
source ./devel/setup.bash
catkin_make -DCMAKE_BUILD_TYPE=Debug --force-cmake
sleep 1
rosrun --prefix 'valgrind --leak-check=full --track-origins=yes -v' bound_est Bound_Est ccw 2> temp_valgrind.txt


